version: '2'
services:
  db:
    image: postgres
    container_name: postgre
    environment:
      DB_HOST: db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: redmine
    volumes:
       - db_data:/var/lib/mysql
    ports:
      - "5432:5432"
  web:
    build: .
    command: rails server -b 3000
    volumes:
      - .:/usr/src/ruby
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      DB_USER: root
      DB_NAME: redmine
      DB_PASSWORD: root
      DB_HOST: db
      DB_HOST_PORT: '5432'
      RAILS_ENV: production


volumes:
  db_data:
    driver: local

networks:
  connection:
    driver: bridge

